//
// Created by cn on 2019/5/2.
//

#ifndef DRIVER_INC_UM2XXOPCODE_H_
#define DRIVER_INC_UM2XXOPCODE_H_

namespace um2xx{

enum opcode{
  OP_GET_HARDWARE_VERSION=0x00,
  OP_GET_HARDWARE_VERSION_ACK=0x01,
  OP_GET_FIRMWARE_VERSION=0x02,
  OP_GET_FIRMWARE_VERSION_ACK=0x03,
  OP_GET_MODULE_ID=0x04,
  OP_GET_MODULE_ID_ACK=0x05,
  OP_FIND_TAG_SIGNLE=0x80,
  OP_FIND_TAG_SIGNLE_ACK=0x81,
  OP_FIND_TAGS_MULTI =0x82,
  OP_FIND_TAGS_MULTI_ACK =0x83,
  OP_FIND_TAGS_STOP = 0x8C
};


}

#endif //DRIVER_INC_UM2XXOPCODE_H_
